import { StyleSheet } from 'react-native';

export const colors = {
  navy: '#233A5E',
  gold: '#F1E4C8',
  slateGray: '#64748B',
  darkGray: '#4B5563',
  lightGray: '#8A95A6',
  charcoal: '#0F172A',
  white: '#FFFFFF',
  lightBg: '#F5F7FB',
  cardBg: '#FFFFFF',
  inputBg: '#F8FAFC',
  mutedBg: '#F8FAFC',
  softGray: '#CBD5E1',
  borderGray: '#E2E8F0',
  accentBorder: '#F1F5F9',
  navyTint: '#E9EEF7',
  rustTint: '#F2E0D7',
  goldTint: '#F4EAD2',
  errorRed: '#EF4444',
  rustBrown: '#8A5B1D',
  warningYellow: '#FFF8E8',
};

export const styles = StyleSheet.create({
  screenRoot: {
    flex: 1,
    backgroundColor: colors.lightBg,
  },
  centeredScreen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    backgroundColor: colors.lightBg,
  },
  container: {
    flex: 1,
    backgroundColor: colors.lightBg,
  },
  screenContentScroll: {
    paddingHorizontal: 20,
    paddingVertical: 20,
    paddingBottom: 120,
  },
  screenContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 6,
    paddingBottom: 100,
    backgroundColor: colors.lightBg,
  },
  authScreen: {
    flex: 1,
    backgroundColor: colors.lightBg,
  },
  authScroll: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingVertical: 24,
    justifyContent: 'center',
  },
  onboardHeader: {
    marginBottom: 28,
  },
  replyScreenContent: {
    paddingHorizontal: 0,
    paddingBottom: 140,
  },
  brandWrap: {
    alignItems: 'center',
    marginBottom: 60,
  },
  brandBadge: {
    width: 72,
    height: 72,
    borderRadius: 24,
    backgroundColor: colors.navy,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    shadowColor: colors.navy,
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  brandBadgeLarge: {
    width: 88,
    height: 88,
    borderRadius: 28,
    backgroundColor: colors.navy,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 28,
    shadowColor: colors.navy,
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  brandBadgeText: {
    color: colors.white,
    fontSize: 28,
    fontWeight: '700',
    letterSpacing: -1,
  },
  brandTitle: {
    fontSize: 32,
    color: colors.charcoal,
    fontWeight: '700',
    letterSpacing: -0.5,
  },
  brandTitleLarge: {
    fontSize: 40,
    color: colors.charcoal,
    fontWeight: '700',
    letterSpacing: -1.5,
    marginBottom: 12,
  },
  brandSubtitle: {
    fontSize: 15,
    color: colors.slateGray,
    textAlign: 'center',
    marginTop: 10,
    lineHeight: 23,
  },
  brandSubtitleLarge: {
    fontSize: 16,
    color: colors.darkGray,
    textAlign: 'center',
    marginBottom: 32,
    lineHeight: 25,
    maxWidth: 300,
  },
  brandSubtitleAuth: {
    fontSize: 14,
    color: colors.slateGray,
    textAlign: 'center',
    marginTop: 12,
    lineHeight: 22,
  },
  descriptionText: {
    fontSize: 14,
    color: colors.slateGray,
    lineHeight: 22,
    marginTop: 6,
  },
  dotRow: {
    flexDirection: 'row',
    gap: 8,
    marginVertical: 32,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.softGray,
  },
  dotActive: {
    width: 22,
    backgroundColor: colors.navy,
    borderRadius: 4,
  },
  card: {
    backgroundColor: colors.white,
    borderRadius: 24,
    padding: 24,
    shadowColor: colors.charcoal,
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
    borderWidth: 1,
    borderColor: colors.accentBorder,
  },
  cardAuth: {
    backgroundColor: colors.white,
    borderRadius: 24,
    padding: 24,
    shadowColor: colors.charcoal,
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
    borderWidth: 1,
    borderColor: colors.accentBorder,
  },
  connectionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 20,
    padding: 16,
    marginBottom: 14,
    shadowColor: colors.charcoal,
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
    borderWidth: 1,
    borderColor: colors.accentBorder,
  },
  listCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    shadowColor: colors.charcoal,
    shadowOpacity: 0.04,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 1,
    borderWidth: 1,
    borderColor: colors.accentBorder,
  },
  cardEyebrow: {
    fontSize: 12,
    color: colors.slateGray,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    fontWeight: '600',
    marginBottom: 8,
  },
  cardTitle: {
    fontSize: 24,
    color: colors.charcoal,
    fontWeight: '700',
    letterSpacing: -0.5,
    marginBottom: 20,
    lineHeight: 32,
  },
  wrapper: {
    position: 'relative',
    justifyContent: 'center',
  },
  inputWithToggle: {
    paddingRight: 56, // room for "Show"/"Hide" text so it doesn't overlap
  },
  toggleButton: {
    position: 'absolute',
    right: 14,
    top: 0,
    bottom: 14,
    justifyContent: 'center',
    zIndex: 10,
  },
  toggleIcon: { width: 20, height: 20 },
  toggleText: {
    color: '#4A6CF7', // match your accent color
    fontSize: 13,
    fontWeight: '600',
  },
  input: {
    borderWidth: 1.5,
    borderColor: colors.borderGray,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 13,
    marginBottom: 14,
    fontSize: 15,
    color: colors.charcoal,
    backgroundColor: colors.inputBg,
    fontWeight: '500',
  },
  inputFocused: {
    borderColor: colors.navy,
    backgroundColor: colors.white,
    shadowColor: colors.navy,
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  primaryButton: {
    backgroundColor: colors.navy,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.navy,
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  primaryButtonLarge: {
    paddingVertical: 16,
    borderRadius: 16,
    minWidth: 180,
    shadowColor: colors.navy,
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
  },
  primaryButtonFull: {
    backgroundColor: colors.navy,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    marginVertical: 8,
    shadowColor: colors.navy,
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  primaryButtonText: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  secondaryButton: {
    backgroundColor: colors.gold,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 18,
    alignSelf: 'flex-start',
    marginTop: 12,
    shadowColor: colors.rustBrown,
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  secondaryButtonText: {
    color: colors.rustBrown,
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  ghostButtonSmall: {
    backgroundColor: colors.navyTint,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#D9E1F0',
  },
  ghostButtonTextSmall: {
    color: colors.navy,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  ghostButton: {
    backgroundColor: colors.inputBg,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: colors.borderGray,
  },
  ghostButtonText: {
    color: colors.navy,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  linkText: {
    color: colors.navy,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 12,
  },
  linkTextAuth: {
    color: colors.navy,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 12,
  },
  linkTextPrimary: {
    color: colors.slateGray,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 16,
  },
  dashboardHeader: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  backRow: {
    marginTop: 6,
    marginBottom: 6,
  },
  eyebrow: {
    color: colors.slateGray,
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    fontWeight: '600',
  },
  title: {
    fontSize: 26,
    color: colors.charcoal,
    fontWeight: '700',
    letterSpacing: -0.5,
    marginTop: 6,
    lineHeight: 32,
  },
  h2: {
    fontSize: 26,
    color: colors.charcoal,
    fontWeight: '700',
    letterSpacing: -0.5,
    marginTop: 8,
    lineHeight: 32,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.gold,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: colors.rustBrown,
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  avatarText: {
    color: colors.rustBrown,
    fontWeight: '700',
    fontSize: 16,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  logoutBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderColor: colors.borderGray,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoutIcon: {
    fontSize: 18,
    color: colors.slateGray,
  },
  // Toggle switch styles
  toggleTrack: {
    width: 46,
    height: 26,
    borderRadius: 13,
    backgroundColor: colors.softGray,
    justifyContent: 'center',
    paddingHorizontal: 3,
    borderWidth: 1,
    borderColor: '#B8C5D6',
  },
  toggleTrackOn: {
    backgroundColor: colors.navy,
    borderColor: colors.navy,
  },
  toggleThumb: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.white,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
    elevation: 2,
    alignSelf: 'flex-start',
  },
  toggleThumbOn: {
    alignSelf: 'flex-end',
  },
  // Pill active / off variants
  pillActive: {
    backgroundColor: colors.navyTint,
    borderColor: '#D9E1F0',
  },
  pillOff: {
    backgroundColor: colors.mutedBg,
    borderColor: colors.borderGray,
  },
  pillTextOff: {
    color: colors.lightGray,
  },
  // Splash screen layout
  splashRoot: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.lightBg,
  },
  splashSlide: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    width: '100%',
  },
  splashActions: {
    width: '100%',
    paddingBottom: 32,
    alignItems: 'center',
    gap: 4,
  },
  brandBadgeTextLarge: {
    color: colors.white,
    fontSize: 40,
    fontWeight: '700',
    letterSpacing: -1,
  },
  content: {
    paddingHorizontal: 20,
    paddingBottom: 110,
    paddingTop: 4,
  },
  heroCard: {
    backgroundColor: colors.white,
    borderRadius: 24,
    padding: 24,
    marginBottom: 24,
    shadowColor: colors.charcoal,
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
    borderWidth: 1,
    borderColor: colors.accentBorder,
  },
  heroEyebrow: {
    color: colors.slateGray,
    fontSize: 12,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 8,
    fontWeight: '600',
  },
  heroTitle: {
    fontSize: 22,
    color: colors.charcoal,
    fontWeight: '700',
    marginBottom: 10,
    lineHeight: 30,
    letterSpacing: -0.3,
  },
  heroText: {
    color: colors.darkGray,
    lineHeight: 23,
    fontSize: 15,
    marginBottom: 16,
  },
  sectionHeader: {
    marginBottom: 12,
    marginTop: 22,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.charcoal,
    letterSpacing: -0.2,
  },
  moduleCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    shadowColor: colors.charcoal,
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
    borderWidth: 1,
    borderColor: colors.accentBorder,
  },
  iconWrap: {
    width: 48,
    height: 48,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  navyTint: {
    backgroundColor: colors.navyTint,
  },
  rustTint: {
    backgroundColor: colors.rustTint,
  },
  goldTint: {
    backgroundColor: colors.goldTint,
  },
  iconText: {
    fontSize: 22,
  },
  moduleBody: {
    flex: 1,
  },
  moduleBodyExpanded: {
    flex: 1,
  },
  moduleTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.charcoal,
    letterSpacing: -0.2,
  },
  moduleSub: {
    marginTop: 3,
    color: colors.slateGray,
    fontSize: 13,
  },
  searchBox: {
    backgroundColor: colors.white,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 4,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: colors.borderGray,
    shadowColor: colors.charcoal,
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },

  searchInput: {
    flex: 1,
    color: colors.charcoal,
    fontSize: 15,
    paddingVertical: 12,
    fontWeight: '500',
  },

  audioWaveformContainer: {
    flex: 1,
    justifyContent: 'center',
    overflow: 'hidden',
  },

  iconButton: {
    padding: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultCard: {
    backgroundColor: colors.white,
    borderRadius: 18,
    padding: 16,
    marginTop: 12,
    shadowColor: colors.charcoal,
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
    borderWidth: 1,
    borderColor: colors.accentBorder,
  },
  badgeRow: {
    flexDirection: 'row',
    gap: 8,
  },
  badge: {
    backgroundColor: colors.navyTint,
    borderRadius: 8,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#D9E1F0',
  },
  badgeText: {
    color: colors.navy,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  inboxCard: {
    backgroundColor: colors.white,
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    shadowColor: colors.charcoal,
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
    borderWidth: 1,
    borderColor: colors.accentBorder,
  },
  inboxCardActive: {
    backgroundColor: colors.white,
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    shadowColor: colors.navy,
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
    borderWidth: 1.5,
    borderColor: colors.navy,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  inboxCardInactive: {
    backgroundColor: colors.mutedBg,
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.borderGray,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  inboxCardLeft: {
    flex: 1,
  },
  inboxTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.charcoal,
    letterSpacing: -0.2,
  },
  inboxTitleSub: {
    fontSize: 13,
    color: colors.slateGray,
    marginTop: 2,
    fontWeight: '500',
  },
  inboxText: {
    marginTop: 5,
    color: colors.slateGray,
    fontSize: 12,
    lineHeight: 18,
  },
  inboxCardMuted: {
    backgroundColor: colors.mutedBg,
    borderRadius: 18,
    padding: 14,
    marginBottom: 10,
  },
  inboxMutedIcon: {
    fontSize: 20,
    color: colors.softGray,
  },
  priorityBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.errorRed,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 12,
  },
  priorityBadgeText: {
    color: colors.white,
    fontWeight: '700',
    fontSize: 18,
  },
  bubbleCard: {
    backgroundColor: colors.white,
    borderRadius: 18,
    padding: 16,
    marginBottom: 20,
    marginHorizontal: 20,
    shadowColor: colors.charcoal,
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
    borderWidth: 1,
    borderColor: colors.accentBorder,
  },
  bubbleText: {
    color: colors.darkGray,
    lineHeight: 23,
    fontSize: 15,
    fontWeight: '500',
  },
  centerLabel: {
    textAlign: 'center',
    color: colors.slateGray,
    marginBottom: 18,
    marginTop: 8,
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  micRing: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: colors.navy,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 14,
    shadowColor: colors.navy,
    shadowOpacity: 0.12,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  micRingLarge: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: colors.navy,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginVertical: 28,
    shadowColor: colors.navy,
    shadowOpacity: 0.15,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  micIcon: {
    fontSize: 28,
  },
  micIconLarge: {
    fontSize: 42,
  },
  waveformContainer: {
    position: 'absolute',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  waveformBar: {
    width: 3,
    borderRadius: 2,
    backgroundColor: '#FFD700',
    opacity: 0.7,
  },
  hintText: {
    textAlign: 'center',
    color: colors.slateGray,
    marginBottom: 20,
    fontSize: 13,
    fontWeight: '500',
  },
  draftBox: {
    backgroundColor: colors.warningYellow,
    borderRadius: 18,
    padding: 16,
    marginTop: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.gold,
  },
  draftBoxEnhanced: {
    backgroundColor: colors.warningYellow,
    borderRadius: 18,
    padding: 18,
    marginHorizontal: 20,
    marginVertical: 16,
    borderWidth: 1.5,
    borderColor: colors.gold,
    shadowColor: colors.rustBrown,
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  draftStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: colors.gold,
    gap: 6,
  },
  draftStatusDot: {
    fontSize: 10,
    color: colors.rustBrown,
  },
  draftStatusText: {
    fontSize: 12,
    color: colors.rustBrown,
    fontWeight: '600',
  },
  replyLabel: {
    fontSize: 12,
    color: colors.rustBrown,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginBottom: 8,
    fontWeight: '700',
  },
  replyCopy: {
    color: colors.darkGray,
    lineHeight: 23,
    fontSize: 15,
    fontWeight: '500',
  },
  confirmWrap: {
    alignItems: 'center',
    paddingTop: 32,
    paddingHorizontal: 20,
  },
  checkBadge: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.navyTint,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
    shadowColor: colors.navy,
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
    borderWidth: 1,
    borderColor: '#D9E1F0',
  },
  checkText: {
    color: colors.navy,
    fontSize: 32,
    fontWeight: '700',
  },
  mutedText: {
    color: colors.slateGray,
    fontSize: 14,
    textAlign: 'center',
    marginTop: 8,
    lineHeight: 20,
  },
  receiptCard: {
    backgroundColor: colors.white,
    borderRadius: 18,
    padding: 18,
    width: '100%',
    marginTop: 20,
    borderWidth: 1,
    borderColor: colors.borderGray,
    shadowColor: colors.charcoal,
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  receiptRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.accentBorder,
  },
  receiptLabel: {
    color: colors.slateGray,
    fontSize: 13,
    fontWeight: '600',
  },
  receiptValue: {
    color: colors.charcoal,
    fontWeight: '700',
    fontSize: 13,
    maxWidth: '60%',
    textAlign: 'right',
    letterSpacing: -0.2,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomColor: '#EEF2F7',
    borderBottomWidth: 1,
  },
  rowTitle: {
    color: colors.charcoal,
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: -0.2,
  },
  rowSub: {
    marginTop: 4,
    color: colors.slateGray,
    fontSize: 13,
    lineHeight: 18,
  },
  rowIcon: {
    fontSize: 22,
    color: colors.softGray,
  },
  pill: {
    backgroundColor: colors.navyTint,
    borderRadius: 20,
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#D9E1F0',
  },
  pillText: {
    color: colors.navy,
    fontWeight: '700',
    fontSize: 11,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  switch: {
    width: 44,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.softGray,
    borderWidth: 1,
    borderColor: '#B8C5D6',
  },
  tabBar: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 16,
    backgroundColor: colors.white,
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 10,
    flexDirection: 'row',
    shadowColor: colors.charcoal,
    shadowOpacity: 0.1,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
    borderWidth: 1,
    borderColor: colors.accentBorder,
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 14,
  },
  activeTab: {
    backgroundColor: colors.navyTint,
  },
  tabIcon: {
    fontSize: 18,
  },
  tabLabel: {
    marginTop: 4,
    fontSize: 10,
    color: colors.slateGray,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  activeTabLabel: {
    color: colors.navy,
  },
  marginTop24: {
    marginTop: 24,
  },

  // ── Subscribe Screen ──────────────────────────────────
  subscribeScroll: {
    paddingHorizontal: 24,
    paddingVertical: 28,
    paddingBottom: 48,
  },
  subscribeBrandWrap: {
    alignItems: 'center',
    marginBottom: 28,
  },
  subscribeTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: colors.charcoal,
    letterSpacing: -0.5,
    marginTop: 16,
    textAlign: 'center',
  },
  subscribeSubtitle: {
    fontSize: 14,
    color: colors.slateGray,
    textAlign: 'center',
    marginTop: 8,
    lineHeight: 22,
  },
  subscribePriceCard: {
    backgroundColor: colors.white,
    borderRadius: 24,
    padding: 24,
    marginBottom: 16,
    borderWidth: 1.5,
    borderColor: colors.navy,
    shadowColor: colors.navy,
    shadowOpacity: 0.1,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  subscribePriceBadge: {
    alignSelf: 'flex-start',
    backgroundColor: colors.navy,
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 10,
    marginBottom: 16,
  },
  subscribePriceBadgeText: {
    color: colors.white,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1,
  },
  subscribePriceRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginBottom: 16,
    gap: 10,
  },
  subscribePriceAmount: {
    fontSize: 52,
    fontWeight: '800',
    color: colors.charcoal,
    letterSpacing: -2,
    lineHeight: 56,
  },
  subscribePriceMeta: {
    paddingBottom: 6,
  },
  subscribePricePer: {
    fontSize: 16,
    color: colors.slateGray,
    fontWeight: '600',
  },
  subscribePriceBilled: {
    fontSize: 12,
    color: colors.lightGray,
    marginTop: 2,
  },
  subscribeDivider: {
    height: 1,
    backgroundColor: colors.accentBorder,
    marginBottom: 16,
  },
  subscribeFeaturesLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.slateGray,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 12,
  },
  subscribeFeatureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  subscribeFeatureIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  subscribeFeatureBody: {
    flex: 1,
  },
  subscribeFeatureTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.charcoal,
    letterSpacing: -0.1,
  },
  subscribeFeatureSub: {
    fontSize: 12,
    color: colors.slateGray,
    marginTop: 1,
  },
  subscribeCheckmark: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.navy,
    marginLeft: 8,
  },
  subscribeGuaranteeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.navyTint,
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#D9E1F0',
  },
  subscribeGuaranteeIcon: {
    fontSize: 22,
    marginRight: 12,
  },
  subscribeGuaranteeBody: {
    flex: 1,
  },
  subscribeGuaranteeTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.navy,
  },
  subscribeGuaranteeSub: {
    fontSize: 12,
    color: colors.slateGray,
    marginTop: 2,
    lineHeight: 18,
  },
  subscribeBackLink: {
    alignItems: 'center',
    marginTop: 14,
    marginBottom: 6,
  },
  subscribeBackText: {
    fontSize: 13,
    color: colors.slateGray,
    fontWeight: '600',
  },
  subscribeLegal: {
    fontSize: 11,
    color: colors.lightGray,
    textAlign: 'center',
    lineHeight: 17,
    marginTop: 12,
  },

  // ── Home Screen – TODO List ───────────────────────────
  todoSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    marginTop: 22,
  },
  todoProgress: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.slateGray,
  },
  todoProgressBar: {
    height: 6,
    backgroundColor: colors.borderGray,
    borderRadius: 3,
    marginBottom: 14,
    overflow: 'hidden',
  },
  todoProgressFill: {
    height: '100%',
    backgroundColor: colors.navy,
    borderRadius: 3,
  },
  todoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 10,
    shadowColor: colors.charcoal,
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
    borderWidth: 1,
    borderColor: colors.accentBorder,
  },
  todoCardDone: {
    backgroundColor: colors.mutedBg,
    borderColor: colors.borderGray,
    shadowOpacity: 0,
    elevation: 0,
  },
  todoCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: colors.softGray,
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    flexShrink: 0,
  },
  todoCheckboxDone: {
    backgroundColor: colors.navy,
    borderColor: colors.navy,
  },
  todoCheckmark: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '700',
  },
  todoBody: {
    flex: 1,
  },
  todoLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.charcoal,
    letterSpacing: -0.1,
    lineHeight: 20,
  },
  todoLabelDone: {
    color: colors.lightGray,
    textDecorationLine: 'line-through',
  },
  todoPriorityDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginLeft: 10,
    flexShrink: 0,
  },
  brandLogo: {
    width: 80,
    height: 80,
  },
  resultCardEnhanced: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    marginBottom: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    overflow: 'hidden',
  },

  resultCardTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },

  resultTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
  },

  resultMeta: {
    marginTop: 4,
    fontSize: 13,
    lineHeight: 18,
    color: '#6B7280',
  },

  resultPrice: {
    marginLeft: 12,
    fontSize: 14,
    fontWeight: '700',
    color: '#111827',
  },

  reasonContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 14,
    marginBottom: 14,
    paddingHorizontal: 12,
    paddingVertical: 11,
    borderRadius: 10,
    backgroundColor: '#FFF9E8',
    borderWidth: 1,
    borderColor: '#F3E8C0',
  },

  reasonIconContainer: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF1B8',
  },

  reasonContent: {
    flex: 1,
    marginLeft: 9,
  },

  reasonLabel: {
    marginBottom: 2,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.2,
    color: '#7C5C00',
    textTransform: 'uppercase',
  },

  reasonText: {
    fontSize: 13,
    lineHeight: 18,
    color: '#5F4B16',
  },
  resultCardBottom: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  badgeContainer: {
    flex: 1,
  },
  resultMapButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
    backgroundColor: '#F3F4F6',
  },
});

export default styles;
